[package]
name = "tags2"
publish = false
description = "TBA"
license = "ISC"
repository = "https://github.com/ctsrc/repotools/tree/master/tags2"
version = "0.0.1"
authors = ["Erik Nordstrøm <erik@nordstroem.no>"]
edition = "2018"

[[bin]]
name = "tags"
path = "src/main.rs"

[dependencies]
