[workspace]

members = [
  "commands/dp2",
  "commands/aa2",
  "commands/st2",
  "commands/di2",
  "commands/cm2",
  "commands/pu2",
  "commands/le2",
  "commands/tag2",
  "commands/tags2",
  "commands/rmtag2",
]

exclude = [
  "repotools",
]
