[package]
name = "tags2"
description = "TBA"
license = "ISC"
readme = "README.md"
repository = "https://github.com/ctsrc/repotools/tree/master/tags2"
version = "0.0.0"
authors = ["Erik Nordstrøm <erik@nordstroem.no>"]
edition = "2018"

[[bin]]
name = "tags"
path = "src/main.rs"

[dependencies]
